### ISSUE TITLE
Suggestion: Adding Unique Hash

### ISSUE THREAD

**Issue by centuryx476** [alfredosa/devtime.nvim#3]
Is there a way to add a column that gives a unique hash. Call it "DataHash" or "IntegrityHash".

Purpose: When copying over data to another SQL table I want to do a compare and not duplicate any records. And a clean way of doing that is by having a unique hash for every row.

**Comment by alfredosa** [comment]
A random twist here, can you use the timestamp as the unique? You can create a time series out of it. There will never be a duplicate on timestamp

**Comment by centuryx476** [comment]
> A random twist here, can you use the timestamp as the unique? You can create a time series out of it. There will never be a duplicate on timestamp

It is guaranteed that every entry will have a unique time stamp ?

**Comment by alfredosa** [comment]
Yeah, this is based on buffer exit, so you won't have 2 entries of the same time and type and file. Potentially if you have to make sure that the row is unique, the constraint should be time and file. That ensures that you can have uniqueness across your dbs (diff devices)
